version: "3"
services:
  catchmytask:
    container_name: catchmytask
    image: catchmytask:latest
    # image: us-central1-docker.pkg.dev/dpwanjala-app/images/catchmyvibe-api:latest
    environment:
      - NEXT_PUBLIC_API_URL=https://api.catchmytask.com
      - NEXTAUTH_URL='https://api.catchmytask.com'
      - NEXTAUTH_SECRET='mltX6eywPIK9+UCojZqDpXN+dFdYsP2vLH/0zu0wths='
      - AZURE_AD_CLIENT_ID="ba1ec8c5-35b4-4fc5-90bb-1b1df32daf4b"
      - AZURE_AD_CLIENT_SECRET="5rY8Q~tggJfgIrfrk4dQXmjo1~Lgnack7kIIaas7"
      - AZURE_AD_TENANT_ID="93808eb2-c7d2-43d0-9bed-b2e4f5e8665f"
    ports:
      - "3000:3000"
    build: .
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catchmytask.rule=Host(`catchmytask.com`)"
      - "traefik.http.routers.catchmytask.entrypoints=websecure"
      - "traefik.http.services.catchmytask.loadbalancer.server.port=3000"
      - "traefik.http.routers.catchmytask.tls=true"
      - "traefik.http.routers.catchmytask.tls.certresolver=letsencrypt"
networks:
  web:
    external: true
