version: "3"
services:
  catchmytask:
    container_name: catchmytask
    image: catchmytask:latest
    # hostname: redis-commander
    # restart: always
    environment:
      - NEXT_PUBLIC_CMT_API_BASEURL=http://localhost:8001
    ports:
      - "3000:3000"
    networks:
      - web
    command: cross-env NEXT_PUBLIC_CMT_API_BASEURL=http://localhost:8001 npm run start
  # sst-tools:
  #   image: devspace:latest
  # image: us-central1-docker.pkg.dev/dpwanjala-app/images/catchmyvibe-api:latest
  # build: .
  #     labels:
  #       - 'traefik.enable=true'
  #       - 'traefik.http.routers.catchmyvibe-api.rule=Host(`catchmyvibe-api.dpwanjala.com`)'
  #       - 'traefik.http.routers.catchmyvibe-api.entrypoints=websecure'
  #       - 'traefik.http.services.catchmyvibe-api.loadbalancer.server.port=80'
  #       - 'traefik.http.routers.catchmyvibe-api.tls=true'
  #       - 'traefik.http.routers.catchmyvibe-api.tls.certresolver=letsencrypt'
  # ports:
  #   - 81:80
  # networks:
  #   - web
  # command: streamlit run main-generate-schedule-change-email.py --server.port 8501
  # command: python main.py
  # environment:
  #   - PORT=80
networks:
  web:
    external: true
