use std::collections::{HashSet, VecDeque};
use std::path::Path;

use crate::config::{Config, StateMachine};
use crate::error::Result;

/// Derive workflow-ordered state list from transitions using BFS from initial states.
/// Returns states in the order they'd be encountered in a typical workflow,
/// with terminal states (done, cancelled) pushed to the end.
pub fn workflow_ordered_states(machine: &StateMachine) -> Vec<String> {
    let terminal: HashSet<&str> = machine
        .states
        .iter()
        .filter(|(_, s)| s.terminal)
        .map(|(n, _)| n.as_str())
        .collect();

    let initial: Vec<&str> = machine
        .states
        .iter()
        .filter(|(_, s)| s.initial)
        .map(|(n, _)| n.as_str())
        .collect();

    let mut bfs_order = Vec::new();
    let mut visited = HashSet::new();
    let mut queue = VecDeque::new();

    for &s in &initial {
        queue.push_back(s.to_string());
        visited.insert(s.to_string());
    }

    while let Some(state) = queue.pop_front() {
        bfs_order.push(state.clone());
        // Follow transitions in definition order
        for t in &machine.transitions {
            if t.from == state && !visited.contains(&t.to) {
                visited.insert(t.to.clone());
                queue.push_back(t.to.clone());
            }
        }
    }

    // Include any states not reachable from initial (shouldn't happen with valid config)
    for name in machine.states.keys() {
        if !visited.contains(name.as_str()) {
            bfs_order.push(name.clone());
        }
    }

    // Partition: non-terminal states first (workflow steps), terminal states last (exits)
    let mut ordered = Vec::new();
    for s in &bfs_order {
        if !terminal.contains(s.as_str()) {
            ordered.push(s.clone());
        }
    }
    for s in &bfs_order {
        if terminal.contains(s.as_str()) {
            ordered.push(s.clone());
        }
    }

    ordered
}

/// Generate .cmt/ABOUT.md from config.
/// This file is committed to git so agents discover it immediately.
pub fn generate_about_file(work_dir: &Path, config: &Config) -> Result<()> {
    let default_machine = config.state_machines.get("default");

    let states_summary = if let Some(machine) = default_machine {
        let ordered = workflow_ordered_states(machine);
        let terminal: HashSet<&str> = machine
            .states
            .iter()
            .filter(|(_, s)| s.terminal)
            .map(|(n, _)| n.as_str())
            .collect();

        // Group terminal states at the end with /
        let non_terminal: Vec<&str> = ordered
            .iter()
            .filter(|s| !terminal.contains(s.as_str()))
            .map(|s| s.as_str())
            .collect();
        let terminal_ordered: Vec<&str> = ordered
            .iter()
            .filter(|s| terminal.contains(s.as_str()))
            .map(|s| s.as_str())
            .collect();

        format!(
            "{} -> {}",
            non_terminal.join(" -> "),
            terminal_ordered.join("/")
        )
    } else {
        "inbox -> ready -> active -> done/cancelled".to_string()
    };

    let content = format!(
        "\
<!-- Auto-generated by catchmytask. Do not edit. Regenerate: cmt init --force -->
# catchmytask

This project uses `cmt` for work management.
Items are Markdown files in `.cmt/items/`.
Run `cmt --help` for commands, `cmt help-agent --json` for agent reference.

Prefix: {} | States: {}
",
        config.project.prefix, states_summary
    );

    crate::storage::atomic_write(&work_dir.join("ABOUT.md"), &content)
}

/// Generate .cmt/CONVENTIONS.md from config.
/// This file is committed to git so agents discover project conventions.
pub fn generate_conventions_file(work_dir: &Path, config: &Config) -> Result<()> {
    let mut content = String::from(
        "<!-- Auto-generated by catchmytask. Do not edit. -->\n\
         # Project Conventions\n\n",
    );

    // IDs section
    let example_id = format!(
        "{:0>width$}",
        1,
        width = config.id.pad_width as usize
    );
    content.push_str(&format!(
        "## IDs\n- Default prefix: {} ({}-digit padding, e.g., {}-{})\n\n",
        config.project.prefix,
        config.id.pad_width,
        config.project.prefix,
        example_id,
    ));

    if !config.id.prefixes.is_empty() {
        content.push_str("Type prefixes:\n");
        for (type_name, prefix) in &config.id.prefixes {
            content.push_str(&format!("- {}: {}\n", type_name, prefix));
        }
        content.push('\n');
    }

    // States section (workflow order, not alphabetical)
    if let Some(machine) = config.state_machines.get("default") {
        content.push_str("## States (default machine)\n");

        let ordered = workflow_ordered_states(machine);
        for name in &ordered {
            if let Some(state) = machine.states.get(name) {
                let mut markers = Vec::new();
                if state.initial {
                    markers.push("initial");
                }
                if state.terminal {
                    markers.push("terminal");
                }
                if markers.is_empty() {
                    content.push_str(&format!("- {}\n", name));
                } else {
                    content.push_str(&format!("- {} ({})\n", name, markers.join(", ")));
                }
            }
        }

        content.push_str("\nTransitions:\n");
        for t in &machine.transitions {
            content.push_str(&format!("  {} -> {}\n", t.from, t.to));
        }
        content.push('\n');
    }

    // Defaults section
    content.push_str("## Defaults\n");
    content.push_str(&format!("- type: {}\n", config.defaults.r#type));
    content.push_str(&format!("- priority: {}\n", config.defaults.priority));
    content.push_str(&format!("- status: {}\n", config.defaults.status));
    if let Some(ref assignee) = config.defaults.assignee {
        content.push_str(&format!("- assignee: {}\n", assignee));
    }
    content.push('\n');

    // Tags section
    content.push_str("## Tags\n");
    content.push_str(&format!(
        "Namespaces: {}\n\n",
        config.tags.namespaces.join(", ")
    ));

    // Git section
    content.push_str("## Git\n");
    content.push_str(&format!("- auto_commit: {}\n", config.git.auto_commit));
    content.push_str(&format!("- commit_prefix: {}\n", config.git.commit_prefix));

    crate::storage::atomic_write(&work_dir.join("CONVENTIONS.md"), &content)
}
