services:
  stormy:
    image: sstgautomations.azurecr.io/catchmytask:latest
    # command: streamlit run main-generate-schedule-change-email.py --server.port 8501
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stormy.rule=Host(`stormy.reports.snowstormtech.com`)"
      - "traefik.http.routers.stormy.entrypoints=websecure"
      - "traefik.http.services.stormy.loadbalancer.server.port=3000"
      - "traefik.http.routers.stormy.tls=true"
      - "traefik.http.routers.stormy.tls.certresolver=letsencrypt"
    networks:
      - web
    ports:
      - 3000:3000
    # environment:
    #   - PORT=8501
    #   - CMT_API_BASE=https://api.reports.snowstormtech.com
networks:
  web:
    external: true
