- name: Ensure /home/{{ ansible_user }}/apps/stormy exists
  file:
    path: /home/{{ ansible_user }}/apps/stormy
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy docker-compose.yml to remote server
  copy:
    src: "docker-compose.yml"
    dest: /home/{{ ansible_user }}/apps/stormy/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
