// import { NotificationsProvider } from "@mantine/notifications";
import { Notifications } from "@mantine/notifications";
import {
  AuthBindings,
  Refine,
  Action,
  IResourceItem,
  useGo,
} from "@refinedev/core";
import { useNotificationProvider } from "@refinedev/mantine";
import routerProvider, { DocumentTitleHandler } from "@refinedev/nextjs-router";
import type { NextPage } from "next";
import { SessionProvider, signIn, signOut, useSession } from "next-auth/react";
import { AppProps } from "next/app";
import { useRouter } from "next/router";
import { accessControlProvider } from "src/access-control-provider";
import BaseLayout from "src/components/Layout";
import defaultApiDataProvider from "../src/default-api-provider";
import { Avatar, createTheme, MantineProvider } from "@mantine/core";
import { initializeLocalDB, saveDatabaseToLocalStorage } from "src/local_db";
// import config from "src/config";
// core styles are required for all packages
// import "@mantine/core/styles.css";
// 👇 Import the mantine-core layer CSS file;
//    this will automatically place it in a `mantine` layer
import "@mantine/core/styles.layer.css";
// 👇 Import the mantine-datatable layer CSS file;
//    this will automatically place it in a `mantine-datatable` layer
import "mantine-datatable/styles.layer.css";
import "@mantine/tiptap/styles.css";
// other css files are required only if
// you are using components from the corresponding package
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";
import "mantine-contextmenu/styles.layer.css";
// import '@mantine/dates/styles.css';
// import '@mantine/dropzone/styles.css';
// import '@mantine/code-highlight/styles.css';
// import "@mantine/core/styles.layer.css";
// import "mantine-datatable/styles.layer.css";
import "../styles/globals.css";
// import { DevtoolsPanel, DevtoolsProvider } from "@refinedev/devtools";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
// import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";
import { registerLicense } from "@syncfusion/ej2-base";
// import { useRuntimeConfig } from "@components/Utils";
import { useAppStore } from "src/store";
import { createContext, useContext, useEffect, useState } from "react";
import { ContextMenuProvider } from "mantine-contextmenu";

// Registering Syncfusion license key
registerLicense(
  "Ngo9BigBOggjHTQxAR8/V1NBaF5cXmZCf1FpRmJGdld5fUVHYVZUTXxaS00DNHVRdkdnWXlfcnRdRGZfU0NyX0o="
);

// Ensure that customTitleHandlerProps has the correct types
interface customTitleHandlerProps {
  resource?: IResourceItem;
  action?: Action;
  params?: Record<string, string | undefined>;
  pathname?: string;
  autoGeneratedTitle: string;
}

const customTitleHandler = ({
  resource,
  action,
  params,
  autoGeneratedTitle,
}: customTitleHandlerProps) => {
  const fetchRuntimeConfig = useAppStore((state) => state.fetchRuntimeConfig);
  const runtimeConfig = useAppStore((state) => state.runtimeConfig);

  useEffect(() => {
    fetchRuntimeConfig();
  }, [fetchRuntimeConfig]);

  let title = runtimeConfig?.APP_NAME; // Default title

  if (resource && action) {
    title = `${resource} ${action} ${params?.id}`;
  }

  return title;
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

// const API_URL = config.API_URL;

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  noLayout?: boolean;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

export type ExtendedNextPage = NextPage & {
  noLayout?: boolean;
};

type ExtendedAppProps = AppProps & {
  Component: ExtendedNextPage;
};

// Create a context for the DuckDB instance
const DuckDBContext = createContext<any>(null);

// Custom hook to use the DuckDB context
export const useDuckDB = () => useContext(DuckDBContext);

const App = (props: React.PropsWithChildren) => {
  const { data: session, status } = useSession();
  const router = useRouter();
  const { to } = router.query;
  const fetchRuntimeConfig = useAppStore((state) => state.fetchRuntimeConfig);
  const runtimeConfig = useAppStore((state) => state.runtimeConfig);
  const { activeSession, activeApplication, activeTask, colorScheme } =
    useAppStore();
  const go = useGo();

  const [dbInstance, setDbInstance] = useState<any>(null);

  useEffect(() => {
    // Initialize DuckDB instance once
    const initializeDB = async () => {
      const db = await initializeLocalDB();
      setDbInstance(db);
    };

    initializeDB();

    // Save the database state to local storage on page unload
    window.addEventListener("beforeunload", saveDatabaseToLocalStorage);

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener("beforeunload", saveDatabaseToLocalStorage);
    };
  }, []);

  useEffect(() => {
    fetchRuntimeConfig();
  }, [fetchRuntimeConfig]);

  if (status === "loading" || !runtimeConfig) {
    return <span>loading...</span>;
  }

  let API_URL = runtimeConfig?.API_URL;

  // Function to return the access token
  const getToken = () => {
    return session?.token?.account?.access_token || ""; // Adjust this based on your session structure
  };
  const getStateIds = () => {
    let stateIds: { [key: string]: any } = {};

    if (activeSession?.id) {
      stateIds["session_id"] = activeSession.id;
    }
    if (activeApplication?.id) {
      stateIds["application_id"] = activeApplication.id;
    }
    if (activeTask?.id) {
      stateIds["task_id"] = activeTask.id;
    }
    if (session?.token?.account?.providerAccountId) {
      stateIds["user_id"] = session.token.account.providerAccountId;
    }

    return stateIds;
  };

  const authProvider: AuthBindings = {
    login: async ({ providerName, email, password }) => {
      if (providerName) {
        signIn(providerName, {
          callbackUrl: to ? to.toString() : "/",
          redirect: true,
        });
        return {
          success: true,
        };
      }

      const signInResponse = await signIn("CredentialsSignIn", {
        email,
        password,
        callbackUrl: to ? to.toString() : "/",
        redirect: false,
      });

      if (!signInResponse) {
        return {
          success: false,
        };
      }

      const { ok, error } = signInResponse;

      if (ok) {
        return {
          success: true,
          redirectTo: "/",
        };
      }

      return {
        success: false,
        error: new Error(error?.toString()),
      };
    },

    logout: async () => {
      signOut({
        redirect: true,
        callbackUrl: "/",
      });

      return {
        success: true,
      };
    },
    onError: async (error) => {
      console.error(error);
      return {
        error,
      };
    },
    check: async () => {
      if (status === "unauthenticated") {
        return {
          authenticated: false,
          redirectTo: "/login",
        };
      }

      return {
        authenticated: true,
      };
    },
    getPermissions: async () => {
      return null;
    },
    getIdentity: async () => {
      if (session?.user) {
        const { user } = session;
        return {
          ...user,
          avatar: user?.image || null,
        };
      }

      return null;
    },
  };

  return (
    <>
      <DuckDBContext.Provider value={dbInstance}>
        <MantineProvider
          theme={theme}
          defaultColorScheme={colorScheme?.scheme || "auto"}
        >
          <ContextMenuProvider>
            <Notifications position="top-right" />
            <Refine
              routerProvider={routerProvider}
              dataProvider={{
                default: defaultApiDataProvider(API_URL, getToken, getStateIds),
              }}
              notificationProvider={useNotificationProvider}
              authProvider={authProvider}
              accessControlProvider={accessControlProvider}
              resources={[
                {
                  name: "home",
                  list: "/home",
                },
                {
                  name: "profile",
                  list: "/profile",
                },
                {
                  name: "applications",
                  list: "/applications",
                  create: "/applications/create",
                  edit: "/applications/edit/:id",
                  show: "/applications/show/:id",
                },

                {
                  name: "sessions",
                  list: "/sessions",
                  create: "/:applicationId/sessions/create",
                  edit: "/:applicationId/sessions/:id/edit",
                  show: "/:applicationId/sessions/:sessionId/tasks/:taskId",
                },
                {
                  name: "tasks",
                  list: "/tasks",
                  show: "/tasks/show/:id",
                },
              ]}
              options={{
                syncWithLocation: true,
                warnWhenUnsavedChanges: true,
                projectId: "OpGcqe-gAGTnn-eW9pDg",
              }}
            >
              {/* <div>
            MYAPP //{" "}
            {JSON.stringify(session?.token?.account?.providerAccountId)}
          </div> */}
              {/* <button
            onClick={() =>
              signOut({
                redirect: true,
                callbackUrl: "/login",
              })
            }
          >
            logout
          </button> */}
              {router.pathname === "/login" && <div>{props.children}</div>}
              {router.pathname !== "/login" && (
                <BaseLayout>{props.children}</BaseLayout>
              )}

              {/* <DocumentTitleHandler handler={customTitleHandler} /> */}
              <ReactQueryDevtools initialIsOpen={false} />
            </Refine>
          </ContextMenuProvider>
        </MantineProvider>
      </DuckDBContext.Provider>
    </>
  );
};

function MyApp({
  Component,
  pageProps: { session, ...pageProps },
}: ExtendedAppProps): JSX.Element {
  return (
    <SessionProvider session={session}>
      <App>
        <Component {...pageProps} />
      </App>
    </SessionProvider>
  );
}

export default MyApp;
