name: Build and Push Node.js Image to Google Cloud Platform

on:
  push:
    branches: [master]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: catchmytask
      PROJECT_ID: dpwanjala-app
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Decode the base64 SSH key (if needed for private repo dependencies)
      - name: Decode SSH Key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.BASE64_SSH_PRIVATE_KEY }}" | base64 -d > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts

      # Install the Cloud SDK to interact with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GITHUBACTIONS_DPWANJALA_APP_IAM_GSERVICEACCOUNT_COM }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      # Install dependencies and build the Next.js app
      - name: Install Dependencies and Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      # Build the Docker image using the decoded SSH key as a build argument
      - name: Build Docker Image
        run: |
          docker build --build-arg SSH_PRIVATE_KEY="$(cat /home/runner/.ssh/id_rsa)" -t $IMAGE_NAME:latest .
          docker images

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
